# coding: utf-8
"""
    Demo API

    No description provided (generated by Openapi Generator https://openapi-generator.tech)
"""


class DefaultApi:
    def get(self):
        return 1

    def post(self):
        return 2
