//! Machine-generated source detection (issue #115).
//!
//! Generated code (protobuf, gRPC, OpenAPI/Swagger SDKs, ORM stubs, …) is regenerated on every
//! change and never hand-edited — the files literally say so in a header marker. Its structural
//! metrics (size, coupling, duplication, docstring/annotation coverage) are artifacts of the
//! *generator*, not of anything a human maintains, so they are noise in a human-maintainability
//! signal. [`is_generated`] is the cheap, deterministic, high-precision test that routes such files
//! into the built-in `generated` profile (kept out of `production` aggregates by default), exactly
//! as the `tests` profile segregates test code.
//!
//! This is **not** "generated code is slop" — provenance is not badness (sloplint's stance). It is
//! the opposite: generated code's numbers are *irrelevant* to the human-code signal, so we measure
//! them separately rather than letting a 34k-line generated module manufacture a "god-module".
//!
//! Detection is **marker-based**, not heuristic-on-content: the markers below are explicit and
//! ubiquitous in generated output, so precision is high and false positives on hand-written code
//! are very unlikely. Only the file *header* is scanned ([`HEADER_LINES`] lines), because every
//! generator emits its marker at the very top.

/// How many leading lines of a file to scan for a generated-code marker. Generators emit their
/// banner in the first few lines (often after a `# coding:` line or a module docstring opener), so
/// a small bound keeps this O(1) per file while comfortably covering real headers.
const HEADER_LINES: usize = 40;

/// Case-insensitive substring markers that, appearing in a file's header, identify it as
/// machine-generated. Kept deliberately specific:
///
/// - `@generated` — the `@generated` convention (Phabricator/Meta, also widely adopted).
/// - `do not edit` — the near-universal banner (`# DO NOT EDIT`, "do not edit ... manually",
///   protobuf's `DO NOT EDIT!`, gRPC's plugin banner, Go-style `Code generated by … DO NOT EDIT`).
/// - `openapi-generator` / `swagger-codegen` — the OpenAPI/Swagger SDK generators (e.g. the
///   Kubernetes Python client: "generated by Openapi Generator https://…/openapi-generator").
///
/// Bare phrases like "generated by" alone are intentionally excluded — they appear in legitimate
/// hand-written headers (e.g. "table generated by hand") and would cost precision.
const MARKERS: &[&str] = &[
    "@generated",
    "do not edit",
    "openapi-generator",
    "swagger-codegen",
];

/// Filename suffixes for the protobuf / gRPC generated-module convention. These files always also
/// carry a `DO NOT EDIT` marker, so this path heuristic is a cheap belt-and-suspenders rather than
/// the primary signal.
const GENERATED_SUFFIXES: &[&str] = &["_pb2.py", "_pb2_grpc.py"];

/// Whether `source` (at `path`) is machine-generated, by a header-marker scan plus the protobuf
/// path convention. Marker matching is case-insensitive; only the first [`HEADER_LINES`] lines are
/// examined. `path` may use either separator — only the trailing filename component is inspected.
pub fn is_generated(source: &str, path: &str) -> bool {
    if has_generated_suffix(path) {
        return true;
    }
    source.lines().take(HEADER_LINES).any(line_has_marker)
}

/// Whether the file name (last `/`- or `\\`-separated component) ends with a generated-module
/// suffix.
fn has_generated_suffix(path: &str) -> bool {
    let file_name = path.rsplit(['/', '\\']).next().unwrap_or(path);
    GENERATED_SUFFIXES
        .iter()
        .any(|suffix| file_name.ends_with(suffix))
}

/// Whether a single header line contains any marker, compared case-insensitively. ASCII-lowercasing
/// the line is enough — every marker is ASCII.
fn line_has_marker(line: &str) -> bool {
    let lower = line.to_ascii_lowercase();
    MARKERS.iter().any(|marker| lower.contains(marker))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn detects_common_generator_banners() {
        // Each of these is a real banner shape from a major generator.
        assert!(is_generated("# @generated by tool\n", "x.py"));
        assert!(is_generated("# DO NOT EDIT\nx = 1\n", "x.py"));
        assert!(is_generated(
            "# Generated by the protocol buffer compiler.  DO NOT EDIT!\n",
            "thing.py"
        ));
        assert!(is_generated(
            "\"\"\"\n    No description (generated by Openapi Generator https://openapi-generator.tech)\n\"\"\"\n",
            "api.py"
        ));
        assert!(is_generated(
            "# NOTE: This class is auto generated by the swagger-codegen program.\n",
            "model.py"
        ));
        // Go-style banner that some Python tools also emit.
        assert!(is_generated(
            "# Code generated by foo. DO NOT EDIT.\n",
            "x.py"
        ));
    }

    #[test]
    fn matching_is_case_insensitive() {
        assert!(is_generated("# do not edit\n", "x.py"));
        assert!(is_generated("# Do Not Edit This File\n", "x.py"));
    }

    #[test]
    fn protobuf_path_convention_counts_even_without_a_marker() {
        // The path heuristic stands alone (these files do carry markers in practice, but we don't
        // rely on it).
        assert!(is_generated("x = 1\n", "proto/thing_pb2.py"));
        assert!(is_generated("x = 1\n", "thing_pb2_grpc.py"));
        // Windows separators are handled when isolating the filename.
        assert!(is_generated("x = 1\n", "a\\b\\thing_pb2.py"));
        // A lookalike that is NOT the convention.
        assert!(!is_generated("x = 1\n", "proto/thing_pb2_helpers.py"));
    }

    #[test]
    fn hand_written_code_is_not_flagged() {
        assert!(!is_generated(
            "import os\n\n\ndef add(a, b):\n    return a + b\n",
            "src/app.py"
        ));
        // A bare "generated by" in prose is intentionally not a marker (precision over recall).
        assert!(!is_generated(
            "# This report table was generated by hand last year.\n",
            "src/app.py"
        ));
    }

    #[test]
    fn marker_below_the_header_window_is_ignored() {
        // A "DO NOT EDIT" buried far past the header (e.g. inside a string constant) must not flip
        // a hand-written file to generated.
        let mut source = String::from("import os\n");
        for i in 0..HEADER_LINES {
            source.push_str(&format!("x{i} = {i}\n"));
        }
        source.push_str("MSG = \"do not edit\"\n");
        assert!(!is_generated(&source, "src/app.py"));
    }
}
